#!/bin/bash

#########################################################

# *** TPC.listThumbnails ***
# View thumbnails of the images located in PWD.
# imageMagik library will be used to creat small version
# of each image in the tmp directory to speed up printing.

# Author: Mustafa Anabtawi
# mustafa@thepolarcat.com
# www.thepolarcat.com

# created om: Dec 16, 2016
# Last update: Dec 22, 2016

#########################################################

#{{{ Variable defaults 

thumbsPerLine=3
thumbW=128	#px
thumbH=128	#px

#static
tmpDir=~/.lsitmp 		#tmp dir to store resized images
charH=17	#px			#estimated height of CLI line in px
rowHeight=8				#height (lines) per row of thumbnails
currentCacheDir=""
fullPath=""
currentCLMN=0
currentROW=1

#}}}

#{{{ Create tmp dir 
function createTmpDir() {
	if [[ ! -e $tmpDir ]] ; then
		mkdir $tmpDir
	fi
}

#}}}

#{{{ Get cursor cordinates 
function getCurCords(){
	local COL
	local ROW
	IFS=';' read -sdR -p $'\E[6n' ROW COL
	if [[ $1 = "X" ]] ; then
		echo "${COL#*[}"
	else
		echo "${ROW#*[}"
	fi
}
#}}}

#{{{ Print file 

#{{{
function print_osc() {
    if [[ $TERM == screen* ]] ; then
        printf "\033Ptmux;\033\033]"
    else
        printf "\033]"
    fi
}
# More of the tmux workaround described above.
function print_st() {
    if [[ $TERM == screen* ]] ; then
        printf "\a\033\\"
    else
        printf "\a"
    fi
}
#}}}

function print_file() {
	fn=$1
	print_osc
	printf "1337;File=%s $1 | base64;"
	VERSION=$(base64 --version 2>&1)
	if [[ "$VERSION" =~ fourmilab ]]; then
		BASE64ARG=-d
	elif [[ "$VERSION" =~ GNU ]]; then
		BASE64ARG=-di
	else
		BASE64ARG=-D
	fi
	one="$(base64 < "$1")"
	printf "%s" $one | base64 $BASE64ARG | wc -c | awk '{printf "size=%d",$1}'
	printf ";inline=1"
	printf ":"
	printf "%s" "$one"
	print_st
}

#}}}

#{{{ Convert thumbnails 
function convertThumbnails(){
	#Make cache dir
	currentCacheDir=$(date "+%H%M%S%d%m%y")
	fullPath="$tmpDir/$currentCacheDir"
	mkdir $fullPath
	find . -maxdepth 1 -type f -name "*.bmp" -o -name "*.jpg" -o -name "*.bmp" -o -name "*.psd" | xargs -I {} convert {} -resize $thumbWx$thumbH! $fullPath"/"{}
}
#}}}

#{{{ Display thumbnails 
function displayThumbs(){
	clear
	local files=($fullPath/*)
	local numfiles=${#files[@]}
	local numRows=$(($numfiles/$thumbsPerLine))
	local index=0
	local newRow=0
	local newCol=0
	local margin=2
	local thumbHeight=7

	currentCol=$(getCurCords X)
	currentRow=$(getCurCords Y)


	for (( i = 0; i <= $numRows; i++ )); do
		newRow=$(( (($currentRow+$thumbHeight+$margin)*$i) + $margin ))
		
		for (( j = 0; j < $thumbsPerLine; j++ )); do
			
			newCol=$((($currentCol+20)*$j));

			if [[ $index -ge $numfiles ]] ; then
				#tput cup 0 $(($newRow+$((7+$margin))))
				break
			fi

			tput cup $newRow $newCol;
			print_file ${files[($index)]}
			g="${files[($index)]##*/}"
			amountToTrim=15
			filenameLength=${#g}
			if [[ $filenameLength -lt $amountToTrim ]] ; then
				amountToTrim=$filenameLength
			fi
			fileName=${g:(-$amountToTrim)}
			tput cup $(($newRow+$thumbHeight+1)) $newCol; printf $fileName
			#echo R$newRow C$newCol 

			((index++))

			#tput setaf 1
		done
	done

	tput cup $(($newRow+$thumbHeight+$margin+1)) 0
}

#}}}

createTmpDir
convertThumbnails
displayThumbs

exit 0
