#!/bin/bash

#########################################################

# *** TERMINUS.thumbnailView ***
# View thumbnails of the images located in PWD.
# imageMagik library will be used to creat small version
# of each image in the tmp directory to speed up printing.

# Author: Mustafa Anabtawi
# mustafa@thepolarcat.com
# www.thepolarcat.com

# created om: Dec 16, 2016
# Last update: Dec 16, 2016

#########################################################

#{{{ Variable defaults 

thumbsPerLine=4
thumbW=128	#px
thumbH=128	#px

#static
tmpDir=~/.tnvtmp 		#tmp dir to store resized images
charH=17	#px			#estimated height of CLI line in px
rowHeight=8				#height (lines) per row of thumbnails
currentCacheDir=""
fullPath=""
currentCLMN=0
currentROW=1

#}}}

#{{{ Create tmp dir 
function createTmpDir() {
	if [[ ! -e $tmpDir ]] ; then
		mkdir $tmpDir
	fi
}

#}}}

#{{{ Print file 

#{{{
function print_osc() {
    if [[ $TERM == screen* ]] ; then
        printf "\033Ptmux;\033\033]"
    else
        printf "\033]"
    fi
}
# More of the tmux workaround described above.
function print_st() {
    if [[ $TERM == screen* ]] ; then
        printf "\a\033\\"
    else
        printf "\a"
    fi
}
#}}}

function print_file() {
	fn=$1
	print_osc
	printf "1337;File=%s $1 | base64;"
	VERSION=$(base64 --version 2>&1)
	if [[ "$VERSION" =~ fourmilab ]]; then
		BASE64ARG=-d
	elif [[ "$VERSION" =~ GNU ]]; then
		BASE64ARG=-di
	else
		BASE64ARG=-D
	fi
	one="$(base64 < "$1")"
	printf "%s" $one | base64 $BASE64ARG | wc -c | awk '{printf "size=%d",$1}'
	printf ";inline=1"
	printf ":"
	printf "%s" "$one"
	print_st
	#printf "\n"
	#X=$((0*$currentCLMN))
	#Y=$((4*$currentROW))
	((currentCLMN++))
	if [ $currentCLMN -eq $thumbsPerLine ] ; then
		currentCLMN=0
		printf "\033[65D"
		# printf "\033[3B"
		nameX=$(( 16*($currentCLMN+1) ))
		printf "\033[16DName\033[$nameX""CName2""\033[$nameX""CName3""\033[$nameX""CName4"


		printf "\n\n"
		((currentROW++))
	else
		printf "\033[7A"
	fi
}
#}}}

#{{{ Convert thumbnails 
function convertThumbnails(){
	#Make cache dir
	currentCacheDir=$(date "+%H%M%S%d%m%y")
	fullPath="$tmpDir/$currentCacheDir"
	mkdir $fullPath
	find . -maxdepth 1 -type f -name "*.bmp" -o -name "*.jpg" -o -name "*.bmp" -o -name "*.psd" | xargs -I {} convert {} -resize $thumbWx$thumbH! $fullPath"/"{}
}
#}}}

#{{{ Display thumbnails 
function displayThumbs(){
	printf "\n\n"
	for file in $fullPath/*; do
		print_file $file
	done
	printf "\n"
}
#}}}

createTmpDir
convertThumbnails
displayThumbs

#printf '\033[7B'

exit 0
